### ISSUE TITLE
Improvement with Twint

### ISSUE THREAD

**Issue by DonaldTsang** [nkratzke/twista#4]
This repo is really promising, but there is one important improvement.
Twint does not require APIs when compared to Tweepy, so it might be good to switch.

**Comment by nkratzke** [comment]
Thanks for this hint. Twint is really a cool tool-suite. However, it is based on Web scraping. According to the Twint documentation, there are still limitations to consider (e.g. not more than 3200 Tweets to be scrapable in one operation).

However, what is more severe. Scraping is dependent on search terms. So, if you do not know what to search for, Twint (and every other scraping solution) is not really helpful. 

But the major use case for Twista is to record continuously a stream of Tweets. For instance, we are continuously recording the complete (or to be more precise the public sample) stream of the German Twitter traffic to detect events that arise suddenly (terror attacks, breaking news, and so on). To give you an impression about the recording volume:

We collect each day hundreds of thousands of tweets of people we are not even aware to be on Twitter! This can not be handled by a search query. A limitation of 3200 Tweets per search operation is far too less for our purposes. Because we developed Twista mainly for our own dataset recording purposes, we do not think that a Twint integration would be worth the effort. Not because Twint is bad software, it fulfils a different purpose. Streaming (Twista) is somehow orthogonal to scraping (Twint).

You may want to check this Zenodo repository that is being recorded using Twista: https://doi.org/10.5281/zenodo.2783954

Because of this different purpose of Twista, we keep using Tweepy so far being aware of the downside that you need Twitter access credentials to use Twista and access to the Twitter Streaming API. However, better performance (streaming instead of scraping) is more important for our use case.

**Comment by DonaldTsang** [comment]
Thanks for the info.
